#!/usr/bin/bash
set -e

if [ $# -le 1 ]; then
    echo "Usage: generate_isrs64.sh <isrs64_gen.c> <isrs64_gen.inc>"
    exit 1
fi

ISRS_GEN_C=$1
ISRS_GEN_ASM=$2

# x86 exceptions with error code
ISRS_WITH_ERROR_CODE="8 10 11 12 13 14 17"

#
# Generate C file
#
echo "// !!! AUTOGENERATED x86_64 ISRs !!!" > $ISRS_GEN_C
echo "#include \"idt64.h\"" >> $ISRS_GEN_C
echo "#include \"gdt.h\"" >> $ISRS_GEN_C
echo "" >> $ISRS_GEN_C

for i in $(seq 0 255); do
    echo "extern void x64_isr_${i}(void);" >> $ISRS_GEN_C
done

echo "" >> $ISRS_GEN_C
echo "void x64_ISR_InitializeGates(void)" >> $ISRS_GEN_C
echo "{" >> $ISRS_GEN_C

for i in $(seq 0 255); do
    echo "    x64_IDT_SetGate(${i}, x64_isr_${i}, GDT_KERNEL_CODE, IDT_FLAG_GATE_32BIT_INT, 0);" >> $ISRS_GEN_C
done

echo "}" >> $ISRS_GEN_C


#
# Generate assembly file
#
echo "; !!! AUTOGENERATED x86_64 ISR stubs !!!" > $ISRS_GEN_ASM

for i in $(seq 0 255); do
    if echo "$ISRS_WITH_ERROR_CODE" | grep -q "\b${i}\b"; then
        echo "ISR64_ERR ${i}" >> $ISRS_GEN_ASM
    else
        echo "ISR64_NOERR ${i}" >> $ISRS_GEN_ASM
    fi
done
