# userspace/SConstruct

import os

TOOLCHAIN = "../../toolchain/x86_64-elf/bin"
CC = os.path.join(TOOLCHAIN, "x86_64-elf-gcc")
AS = os.path.join(TOOLCHAIN, "x86_64-elf-as")
LD = os.path.join(TOOLCHAIN, "x86_64-elf-ld")

env = Environment(
    CC=CC,
    AS=AS,
    LD=LD,
    CFLAGS="-m64 -ffreestanding -nostdlib -fno-pie -fno-stack-protector -Wall -Wextra -Ilibc/include",
    LINKFLAGS="-nostdlib -Wl,-m,elf_x86_64"
)

# Build libc first
SConscript("libc/SConscript", exports="env")

# Build user programs
SConscript("bin/init/SConscript", exports="env")
SConscript("bin/test/SConscript", exports="env")
