import os

project_name   = 'luma-compositor'
build_dir      = 'build'
generated_dir  = os.path.join(build_dir, 'generated')

# Host env for wayland-scanner
host_env = Environment(
    CC  = 'gcc',
    CXX = 'g++',
)

cross_prefix = '../../toolchain/bin/x86_64-linux-musl-'
sysroot      = os.path.expanduser('~/Project/OperatingSystem/sysroot')

# -----------------------------
# TARGET ENVIRONMENT (DEBUG)
# -----------------------------
target_env = Environment(
    CC   = cross_prefix + 'gcc',
    CXX  = cross_prefix + 'g++',
    LINK = cross_prefix + 'g++',

    CPPPATH = [
        '.', 'src', generated_dir,
        os.path.join(sysroot, 'usr/include'),
    ],

    LIBPATH = [
        os.path.join(sysroot, 'usr/lib'),
    ],

    LIBS = [
        'wayland-server',
        'xkbcommon',
        'ffi',
    ],

    # -----------------------------
    # DEBUG FLAGS (IMPORTANT)
    # -----------------------------
    CCFLAGS = [
        '--sysroot=' + sysroot,
        '-g',               # <--- ADD DEBUG SYMBOLS
        '-O0',              # <--- DISABLE OPTIMIZATION
        '-static',
        '-fno-pie',
        '-no-pie',
        '-fno-stack-protector',
        '-fno-exceptions',
        '-fno-rtti',
        '-fno-threadsafe-statics',
    ],

    CXXFLAGS = [
        '--sysroot=' + sysroot,
        '-std=c++17',
        '-g',               # <--- ADD DEBUG SYMBOLS
        '-O0',              # <--- DISABLE OPTIMIZATION
        '-static',
        '-fno-pie',
        '-no-pie',
    ],

    LINKFLAGS = [
        '--sysroot=' + sysroot,
        '-static',
        '-fno-pie',
        '-no-pie',
        '-Wl,-Tlinker.ld',
    ],
)

# dirs
target_env.Execute(Mkdir(build_dir))
target_env.Execute(Mkdir(generated_dir))

generated_dir_node = target_env.Dir(generated_dir)
project_root       = target_env.Dir('#')

# Wayland protocol generation
protocols = [
    project_root.File('protocols/xdg-shell.xml'),
    project_root.File('protocols/wayland.xml'),
]

generated_sources = []

for xml_file in protocols:
    base = os.path.splitext(os.path.basename(xml_file.path))[0]

    c_out = generated_dir_node.File(f"{base}-protocol.c")
    h_out = generated_dir_node.File(f"{base}-protocol.h")

    host_env.Command(
        [c_out, h_out],
        xml_file,
        [
            f'wayland-scanner private-code {xml_file.path} {c_out.path}',
            f'wayland-scanner server-header {xml_file.path} {h_out.path}',
        ]
    )

    generated_sources.append(c_out)

# Sources
sources = [
    'src/main.cpp',
    'src/compositor.cpp',
    'src/compositor_input.cpp',
    'src/compositor_helper.cpp',
] + generated_sources

# Program
program = target_env.Program(
    target=os.path.join(build_dir, project_name),
    source=sources,
)

# # Strip
# target_env.AddPostAction(
#     program,
#     f"{cross_prefix}strip -s $TARGET"
# )

Default(program)
Export('program')
