// syscall_numbers.h
#pragma once

enum {
    SYS_test            = 0,
    SYS_write           = 1,
    SYS_exit            = 2,
    SYS_open            = 3,
    SYS_read            = 4,
    SYS_close           = 5,
    SYS_mmap            = 6,
    SYS_munmap          = 7,
    SYS_mprotect        = 8,
    SYS_brk             = 9,
    SYS_poll            = 10,
    SYS_stat            = 11,
    SYS_fstat           = 12,
    SYS_lseek           = 13,
    SYS_getdents        = 14,
    SYS_dup             = 15,
    SYS_dup2            = 16,
    SYS_fcntl           = 17,
    SYS_pipe            = 18,
    SYS_klog            = 19,
    SYS_clock_gettime   = 20,
    SYS_nanosleep       = 21,
    SYS_socketpair      = 22,
    SYS_sendmsg         = 23,
    SYS_recvmsg         = 24,
    SYS_memfd_create    = 25,
    SYS_ftruncate       = 26,
    SYS_getpid          = 27,
    SYS_getppid         = 28,
    SYS_uname           = 29,
    SYS_getcwd          = 30,
    SYS_madvise         = 31,
    SYS_set_tid_address = 32,
    SYS_prlimit64       = 33,
    SYS_getrandom       = 34,
    SYS_exit_group      = 35,
    SYS_arch_prctl      = 36,
    // later: SYS_socket, ..
};