Import("env")

libc_sources = [
    "src/syscall/musl_syscall.c",
    "src/syscall/syscall.c",
    "src/sys/klog/klog.c",
]

libc_objs = env.Object(libc_sources)

Return("libc_objs")



# Import("env")

# libc_env = env.Clone()

# sources = [
#     "src/stdio/printf.c",
#     "src/unistd/write.c",
#     "src/unistd/exit.c",
#     "src/unistd/open.c",
#     "src/unistd/read.c",
#     "src/unistd/close.c",
#     "src/unistd/lseek.c",
#     "src/unistd/dup.c",
#     "src/unistd/pipe.c",
#     "src/unistd/ftruncate.c",
#     "src/time/clock_gettime.c",
#     "src/time/nanosleep.c",
#     "src/sys/mman/mmap.c",
#     "src/sys/mman/munmap.c",
#     "src/sys/mman/mprotect.c",
#     "src/memory/brk.c",
#     "src/sys/mman/mprotect.c",
#     "src/sys/poll/poll.c",
#     "src/sys/stat/stat.c",
#     "src/sys/dirent/getdents.c",
#     "src/sys/fcntl/fcntl.c",
#     "src/sys/klog/klog.c",
#     "src/sys/mman/memfd_create.c",
#     "src/sys/socket/recvmsg.c",
#     "src/sys/socket/sendmsg.c",
#     "src/socket/socketpair.c",
#     "src/syscall/musl_syscall.c",
#     "src/syscall/syscall.c",
#     "src/string/memset.c",
#     "src/string/memcpy.c",
#     "src/string/memmove.c",
#     "src/string/memcmp.c",
#     "src/string/strlen.c",
#     # "crt/crtbegin.c",
# ]


# crt0 = "crt/crt0.s"

# libc = libc_env.Library("libc", sources + [crt0])

# Export("libc")
