Import("env")

libc_env = env.Clone()

sources = [
    "src/stdio/printf.c",
    "src/unistd/write.c",
    "src/unistd/exit.c",
    "src/unistd/open.c",
    "src/unistd/read.c",
    "src/unistd/close.c",
    "src/unistd/lseek.c",
    "src/unistd/dup.c",
    "src/sys/mman/mmap.c",
    "src/sys/mman/munmap.c",
    "src/sys/mman/mprotect.c",
    "src/memory/brk.c",
    "src/sys/mman/mprotect.c",
    "src/sys/poll/poll.c",
    "src/sys/stat/stat.c",
    "src/sys/dirent/getdents.c",
    "src/sys/fcntl/fcntl.c",
    "src/syscall/syscall.c",
    # "crt/crtbegin.c",
]


crt0 = "crt/crt0.s"

libc = libc_env.Library("libc", sources + [crt0])

Export("libc")
